[build-system]
requires = [
    "setuptools",
    "hatchling"
]

[project]
name = "skillbase"
version = "0.1.0"
description = "Skillbase Tool"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "easydict>=1.13",
    "flask>=3.0.3",
    "jinja2>=3.1.4",
]

[tool]

